jahsjdkel

diff --git a/AnyKernel3/META-INF/com/google/android/update-binary b/AnyKernel3/META-INF/com/google/android/update-binary
--- a/AnyKernel3/META-INF/com/google/android/update-binary
+++ b/AnyKernel3/META-INF/com/google/android/update-binary
@@ -23,11 +23,42 @@ ui_print() {
     shift;
   done;
 }
+
 ui_printfile() {
   while IFS='' read -r line || $BB [[ -n "$line" ]]; do
     ui_print "$line";
   done < $1;
 }
+
+# insert_line <file> <if search string> <before|after> <line match string> <inserted line>
+insert_line() {
+  local offset line;
+  if ! grep -q "$2" $1; then
+    case $3 in
+      before) offset=0;;
+      after) offset=1;;
+    esac;
+    line=$((`grep -n "$4" $1 | head -n1 | cut -d: -f1` + offset));
+    if [ -f $1 -a "$line" ] && [ "$(wc -l $1 | cut -d\  -f1)" -lt "$line" ]; then
+      echo "$5" >> $1;
+    else
+      sed -i "${line}s;^;${5}\n;" $1;
+    fi;
+  fi;
+}
+
+ui_print "××××××××××××××××××××××××××××××××××××××××××××××"
+ui_print "              _   __                                "
+ui_print "             / | / /__  _  ____  _______             "
+ui_print "            /  |/ / _ \| |/_/ / / / ___/              "
+ui_print "           / /|  /  __/>  </ /_/ (__  )              "
+ui_print "          /_/ |_/\___/_/|_|\__,_/____/                "
+ui_print "                                                    "
+ui_print "×××××××××××××××××××××××××××××××××××××××××××××××"
+ui_print "×              Nexus Kernel Lavender              ×"
+ui_print "×××××××××××××××××××××××××××××××××××××××××××××××"
+ui_print " "
+ui_print "× Initializing parameters and properties"
 show_progress() { echo "progress $1 $2" >> $OUTFD; }
 file_getprop() { $BB grep "^$2=" "$1" | $BB tail -n1 | $BB cut -d= -f2-; }
 find_slot() {
@@ -245,7 +276,7 @@ restore_env() {
 debugging() {
   case $($BB basename "$ZIPFILE" .zip) in
     *-debugging)
-      ui_print " " "Creating debugging archive in $DIR...";
+      ui_print "× Creating debugging archive in $DIR!";
       [ -f /tmp/recovery.log ] && local log=/tmp/recovery.log;
       $BB tar -czf "$DIR/anykernel3-$(date +%Y-%m-%d_%H%M%S)-debug.tgz" $AKHOME $log;
     ;;
@@ -267,7 +298,6 @@ abort() {
 do_devicecheck() {
   [ "$(file_getprop anykernel.sh do.devicecheck)" == 1 ] || return 1;
   local device devicename match product testname vendordevice vendorproduct;
-  ui_print "Checking device...";
   device=$(getprop ro.product.device 2>/dev/null);
   product=$(getprop ro.build.product 2>/dev/null);
   vendordevice=$(getprop ro.product.vendor.device 2>/dev/null);
@@ -275,14 +305,14 @@ do_devicecheck() {
   for testname in $($BB grep '^device.name.*=' anykernel.sh | $BB cut -d= -f2-); do
     for devicename in $device $product $vendordevice $vendorproduct; do
       if [ "$devicename" == "$testname" ]; then
-        ui_print "$testname" " ";
+        ui_print "× Device recognised as $testname";
         match=1;
         break 2;
       fi;
     done;
   done;
   if [ ! "$match" ]; then
-    abort " " "Unsupported device. Aborting...";
+    abort "× Unsupported device. Aborting!";
   fi;
 }
 int2ver() {
@@ -297,7 +327,7 @@ int2ver() {
 do_versioncheck() {
   [ "$(file_getprop anykernel.sh supported.versions)" ] || return 1;
   local android_ver hi_ver lo_ver parsed_ver supported supported_ver;
-  ui_print "Checking Android version...";
+  ui_print "× Checking Android version";
   supported_ver=$(file_getprop anykernel.sh supported.versions | $BB tr -d '[:space:]');
   android_ver=$(file_getprop /system/build.prop ro.build.version.release);
   parsed_ver=$(int2ver $android_ver);
@@ -316,15 +346,15 @@ do_versioncheck() {
     done;
   fi;
   if [ "$supported" ]; then
-    ui_print "$android_ver" " ";
+     ui_print "× Detected android version: $android_ver";
   else
-    abort " " "Unsupported Android version. Aborting...";
+    abort "× Unsupported Android version. Aborting!";
   fi;
 }
 do_levelcheck() {
   [ "$(file_getprop anykernel.sh supported.patchlevels)" ] || return 1;
   local android_lvl hi_lvl lo_lvl parsed_lvl supported_lvl;
-  ui_print "Checking Android security patch level...";
+  ui_print "× Checking Android security patch level";
   supported_lvl=$(file_getprop anykernel.sh supported.patchlevels | $BB grep -oE '[0-9]{4}-[0-9]{2}|-');
   android_lvl=$(file_getprop /system/build.prop ro.build.version.security_patch);
   parsed_lvl=$(echo $android_lvl | $BB grep -oE '[0-9]{4}-[0-9]{2}');
@@ -339,9 +369,9 @@ do_levelcheck() {
     hi_lvl=9999-99;
   fi;
   if echo -e "$hi_lvl\n$lo_lvl\n$parsed_lvl" | $BB sort -g | $BB grep -n "$parsed_lvl" | $BB grep -q '^2:'; then
-    ui_print "$android_lvl" " ";
+    ui_print "× Detected android patch level: $android_lvl";
   else
-    abort " " "Unsupported Android security patch level. Aborting...";
+    abort "× Unsupported Android security patch level. Aborting!";
   fi;
 }
 dump_moduleinfo() {
@@ -368,8 +398,8 @@ do_modules() {
   local block modcon moddir modtarget module slot umask;
   if [ "$(file_getprop anykernel.sh do.systemless)" == 1 ]; then
     cd $AKHOME/modules;
-    ui_print " " "Creating kernel helper Magisk module...";
-    if [ -d /data/adb/magisk -a -f $AKHOME/magisk_patched ]; then
+    ui_print "× Creating kernel helper Magisk module";
+    if [ -d /data/adb/magisk -a -f $AKHOME/split_img/.magisk ]; then
       umask=$(umask);
       umask 022;
       moddir=/data/adb/modules/ak3-helper;
@@ -383,11 +413,11 @@ do_modules() {
       $BB cp -f $AKHOME/vertmp $moddir/version;
       umask $umask;
     else
-      ui_print "Magisk installation not found. Skipped!";
+      ui_print "× Magisk installation not found. Skipped!";
     fi;
   else
     cd $AKHOME/modules;
-    ui_print " " "Pushing modules...";
+    ui_print "Pushing modules...";
     if [ -d /dev/block/mapper ]; then
       for block in system vendor product; do
         for slot in "" _a _b; do
@@ -432,14 +462,23 @@ do_modules() {
   cd $AKHOME;
 }
 
+print_extras()
+{
+  android_ver=$(file_getprop /system/build.prop ro.build.version.release);
+  android_lvl=$(file_getprop /system/build.prop ro.build.version.security_patch);
+
+  ui_print "× Detected android version: $android_ver";
+  ui_print "× Detected android patch level: $android_lvl";
+}
+
 show_progress 1.34 5;
-ui_print " ";
+ui_print "";
 cleanup;
 mkdir -p $AKHOME/bin;
 cd $AKHOME;
 unzip -o "$ZIPFILE";
 if [ $? != 0 -o ! "$(ls tools)" ]; then
-  abort "Unzip failed. Aborting...";
+  abort "× Unzip failed. Aborting!";
 fi;
 for ARCH32 in x86 arm; do
   if [ -d $AKHOME/tools/$ARCH32 ]; then
@@ -457,24 +496,17 @@ chmod 755 $BB;
 $BB chmod -R 755 tools bin;
 $BB --install -s bin;
 if [ $? != 0 -o -z "$(ls bin)" ]; then
-  abort "Busybox setup failed. Aborting...";
+  abort "× Busybox setup failed. Aborting!";
 fi;
-
-if [ -f banner ]; then
-  ui_printfile banner;
-  ui_print " " " ";
-fi;
-
-$BB grep -oE 'AK_BASE.*' META-INF/com/google/android/updater-script >&2;
-ui_print " ";
 
 setup_env;
 
 do_devicecheck;
 do_versioncheck;
 do_levelcheck;
+print_extras;
 
-ui_print "Installing...";
+ui_print "× Installing Linux kernel";
 CORE=$($BB grep -oE 'ak.*core.sh' anykernel.sh);
 [ -f tools/$CORE ] || $BB ln -s $AKHOME/tools/ak*-core.sh $AKHOME/tools/$CORE;
 PATH="$AKHOME/bin:$PATH" home=$AKHOME $BB ash anykernel.sh $2;
@@ -491,4 +523,9 @@ if [ "$(file_getprop anykernel.sh do.cleanup)" == 1 ]; then
   cleanup;
 fi;
 
-ui_print " " " " "Done!";
+ui_print "× Successfully flashed kernel!";
+ui_print "× Thank you for using Nexus Kernel!";
+ui_print "× Powered by AnyKernel3 by osm0sis @ xda-developers";
+$BB grep -oE 'AK_BASE.*' META-INF/com/google/android/updater-script >&2;
+ui_print " "
+ui_print "×××××××××××××××××××××××××××××××××××××××××××××××"
